<?xml version="1.0" encoding="utf-8"?>
<WebElementEntity>
    <description>Generated by Katalon AI</description>
    <elementGuidId>74df1b8f-a284-43e5-a8f8-8363c4ffd83c</elementGuidId>
    <imagePath></imagePath>
    <name>link_vinothQademo</name>
    <selectorCollection>
        <entry>
            <key>XPATH</key>
            <value>//body/div[1]/div[1]/div[2]/nav[1]/div[3]/ul[1]/li[3]/ul[1]/li[3]/a[1]</value>
        </entry>
        <entry>
            <key>CSS</key>
            <value>li:nth-of-type(3) &gt; [class="flex\ items-center\ px-3\ py-2\ text-sm\ rounded-md\ text-gray-600\ dark\:text-gray-400\ hover\:bg-gray-50\ dark\:hover\:bg-gray-700"]</value>
        </entry>
        <entry>
            <key>BASIC</key>
            <value>//*[equals(@href,'https://base-component.aut.katalon.com/iframes/{{username}}.html') and equals(@text,'{{username}} QA Demo')]</value>
        </entry>
    </selectorCollection>
    <selectorMethod>XPATH</selectorMethod>
    <smartLocatorCollection>
        <entry>
            <key>SMART_LOCATOR</key>
            <value>[data-test=\"nav-iframes\\/vinoth-demo\"]</value>
        </entry>
    </smartLocatorCollection>
    <smartLocatorEnabled>true</smartLocatorEnabled>
    <tag></tag>
    <useRalativeImagePath>false</useRalativeImagePath>
    <webElementProperties>
        <isSelected>true</isSelected>
        <matchCondition>equals</matchCondition>
        <name>href</name>
        <type>Main</type>
        <value>https://base-component.aut.katalon.com/iframes/{{username}}.html</value>
        <webElementGuid>b3c57c63-de53-48c9-a1f5-f7dcfeed7326</webElementGuid>
    </webElementProperties>
    <webElementProperties>
        <isSelected>true</isSelected>
        <matchCondition>equals</matchCondition>
        <name>text</name>
        <type>Main</type>
        <value>{{username}} QA Demo</value>
        <webElementGuid>b3c57c63-de53-48c9-a1f5-f7dcfeed7326</webElementGuid>
    </webElementProperties>
</WebElementEntity>