<?xml version="1.0" encoding="utf-8"?>
<WebElementEntity>
    <description>Generated by Katalon AI</description>
    <elementGuidId>386e335d-8aa3-475d-b6b4-2c35a3e4203b</elementGuidId>
    <imagePath></imagePath>
    <name>div_comboboxContainer</name>
    <selectorCollection>
        <entry>
            <key>XPATH</key>
            <value>"//body/div[1]/div[1]/div[3]/main[1]/div[1]/div[2]/div[1]/div[1]/div[1]/div[1]"</value>
        </entry>
        <entry>
            <key>CSS</key>
            <value>[class="p-4\ border\ rounded\ bg-yellow-50"] &gt; [class="space-y-3"]</value>
        </entry>
    </selectorCollection>
    <selectorMethod>XPATH</selectorMethod>
    <smartLocatorCollection>
        <entry>
            <key>SMART_LOCATOR</key>
            <value>div:nth-child(${div_comboboxContainer_divNthChild}) &gt; .p-4 &gt; .space-y-3</value>
        </entry>
    </smartLocatorCollection>
    <smartLocatorEnabled>true</smartLocatorEnabled>
    <tag></tag>
    <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>