<?xml version="1.0" encoding="utf-8"?>
<WebElementEntity>
    <description>Generated by Katalon AI</description>
    <elementGuidId>3023b860-01a0-4d19-9d0b-c7d24e43f076</elementGuidId>
    <imagePath></imagePath>
    <name>item_formManagement</name>
    <selectorCollection>
        <entry>
            <key>XPATH</key>
            <value>//body/div[1]/div[1]/div[3]/main[1]/div[1]/div[2]/ul[1]/li[1]</value>
        </entry>
        <entry>
            <key>CSS</key>
            <value>[class="text-sm\ text-gray-700\ space-y-1"] &gt; li:nth-of-type(${item_formManagement_LiNthOfType_2})</value>
        </entry>
    </selectorCollection>
    <selectorMethod>XPATH</selectorMethod>
    <smartLocatorCollection>
        <entry>
            <key>SMART_LOCATOR</key>
            <value>.text-sm &gt; li:nth-child(${item_formManagement_TextSmLiNthChild_1})</value>
        </entry>
    </smartLocatorCollection>
    <smartLocatorEnabled>true</smartLocatorEnabled>
    <tag></tag>
    <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>