<?xml version="1.0" encoding="utf-8"?>
<WebElementEntity>
    <description>Generated by Katalon AI</description>
    <elementGuidId>ed8cded8-ad43-41bb-ab18-ba2ee03b606a</elementGuidId>
    <imagePath></imagePath>
    <name>label_notificationSettings</name>
    <selectorCollection>
        <entry>
            <key>XPATH</key>
            <value>"//body/div[1]/div[1]/div[3]/main[1]/div[1]/div[2]/div[1]/div[1]/div[1]/div[1]/label[1]"</value>
        </entry>
        <entry>
            <key>CSS</key>
            <value>[class="${label_notificationSettings_class}"]</value>
        </entry>
    </selectorCollection>
    <selectorMethod>XPATH</selectorMethod>
    <smartLocatorCollection>
        <entry>
            <key>SMART_LOCATOR</key>
            <value>label &gt;&gt; internal:text=\"${label_notificationSettings_internalText}\"s</value>
        </entry>
    </smartLocatorCollection>
    <smartLocatorEnabled>true</smartLocatorEnabled>
    <tag></tag>
    <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>