<?xml version="1.0" encoding="utf-8"?>
<WebElementEntity>
    <description>Generated by Katalon AI</description>
    <elementGuidId>01d8dd31-4266-468f-b5bf-4df45855c35e</elementGuidId>
    <imagePath></imagePath>
    <name>select_themeLanguageOptions</name>
    <selectorCollection>
        <entry>
            <key>XPATH</key>
            <value>"//body/div[1]/div[1]/div[3]/main[1]/div[1]/div[2]/div[1]/div[1]/div[1]/div[1]/select[1]"</value>
        </entry>
        <entry>
            <key>CSS</key>
            <value>select:nth-of-type(${select_themeLanguageOptions_selectNthOfType})</value>
        </entry>
    </selectorCollection>
    <selectorMethod>XPATH</selectorMethod>
    <smartLocatorCollection>
        <entry>
            <key>SMART_LOCATOR</key>
            <value>select &gt;&gt; nth=${select_themeLanguageOptions_nth}</value>
        </entry>
    </smartLocatorCollection>
    <smartLocatorEnabled>true</smartLocatorEnabled>
    <tag></tag>
    <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>