<?xml version="1.0" encoding="utf-8"?>
<WebElementEntity>
    <description>Generated by Katalon AI</description>
    <elementGuidId>fcf49829-0a95-4f07-bd56-7607b284e865</elementGuidId>
    <imagePath></imagePath>
    <name>link_dynamicElements</name>
    <selectorCollection>
        <entry>
            <key>XPATH</key>
            <value>//body/div[1]/div[1]/div[2]/nav[1]/div[2]/ul[1]/li[2]/a[1]</value>
        </entry>
        <entry>
            <key>CSS</key>
            <value>div:nth-of-type(2) &gt; [class="space-y-1"] &gt; li:nth-of-type(2) &gt; .flex</value>
        </entry>
        <entry>
            <key>BASIC</key>
            <value>//*[equals(@href,'https://base-component.aut.katalon.com/dynamic-elements.html') and equals(@text,'Dynamic Elements')]</value>
        </entry>
    </selectorCollection>
    <selectorMethod>XPATH</selectorMethod>
    <smartLocatorCollection>
        <entry>
            <key>SMART_LOCATOR</key>
            <value>[data-test=\"nav-dynamic-elements\"]</value>
        </entry>
    </smartLocatorCollection>
    <smartLocatorEnabled>true</smartLocatorEnabled>
    <tag></tag>
    <useRalativeImagePath>false</useRalativeImagePath>
    <webElementProperties>
        <isSelected>true</isSelected>
        <matchCondition>equals</matchCondition>
        <name>href</name>
        <type>Main</type>
        <value>https://base-component.aut.katalon.com/dynamic-elements.html</value>
        <webElementGuid>c6fea543-e7ff-4781-88d7-91ce40e64f67</webElementGuid>
    </webElementProperties>
    <webElementProperties>
        <isSelected>true</isSelected>
        <matchCondition>equals</matchCondition>
        <name>text</name>
        <type>Main</type>
        <value>Dynamic Elements</value>
        <webElementGuid>c6fea543-e7ff-4781-88d7-91ce40e64f67</webElementGuid>
    </webElementProperties>
</WebElementEntity>