<?xml version="1.0" encoding="utf-8"?>
<WebElementEntity>
    <description>Generated by Katalon AI</description>
    <elementGuidId>43cca9a8-d564-4fdc-b8a0-2f2dbbe7dd51</elementGuidId>
    <imagePath></imagePath>
    <name>link_fileUpload</name>
    <selectorCollection>
        <entry>
            <key>XPATH</key>
            <value>//body/div[1]/div[1]/div[2]/nav[1]/div[3]/ul[1]/li[1]/a[1]</value>
        </entry>
        <entry>
            <key>CSS</key>
            <value>div:nth-of-type(3) &gt; [class="space-y-1"] &gt; li:nth-of-type(1) &gt; .flex</value>
        </entry>
        <entry>
            <key>BASIC</key>
            <value>//*[equals(@href,'https://base-component.aut.katalon.com/file-upload.html') and equals(@text,'File Upload')]</value>
        </entry>
    </selectorCollection>
    <selectorMethod>XPATH</selectorMethod>
    <smartLocatorCollection>
        <entry>
            <key>SMART_LOCATOR</key>
            <value>[data-test=\"nav-file-upload\"]</value>
        </entry>
    </smartLocatorCollection>
    <smartLocatorEnabled>true</smartLocatorEnabled>
    <tag></tag>
    <useRalativeImagePath>false</useRalativeImagePath>
    <webElementProperties>
        <isSelected>true</isSelected>
        <matchCondition>equals</matchCondition>
        <name>href</name>
        <type>Main</type>
        <value>https://base-component.aut.katalon.com/file-upload.html</value>
        <webElementGuid>b3c57c63-de53-48c9-a1f5-f7dcfeed7326</webElementGuid>
    </webElementProperties>
    <webElementProperties>
        <isSelected>true</isSelected>
        <matchCondition>equals</matchCondition>
        <name>text</name>
        <type>Main</type>
        <value>File Upload</value>
        <webElementGuid>b3c57c63-de53-48c9-a1f5-f7dcfeed7326</webElementGuid>
    </webElementProperties>
</WebElementEntity>