<?xml version="1.0" encoding="utf-8"?>
<WebElementEntity>
    <description>Generated by Katalon AI</description>
    <elementGuidId>9fe8d5c1-25cb-4690-93ce-1e4ef3fa2338</elementGuidId>
    <imagePath></imagePath>
    <name>header_billingDetailsForm</name>
    <selectorCollection>
        <entry>
            <key>XPATH</key>
            <value>//body/div[1]/div[1]/div[3]/main[1]/div[1]/div[2]/div[1]/div[5]/div[1]/h3[1]</value>
        </entry>
        <entry>
            <key>CSS</key>
            <value>[class="p-4\ border\ rounded\ bg-yellow-50"] &gt; .font-semibold</value>
        </entry>
    </selectorCollection>
    <selectorMethod>XPATH</selectorMethod>
    <smartLocatorCollection>
        <entry>
            <key>SMART_LOCATOR</key>
            <value>div:nth-child(5) &gt; .p-4 &gt; .font-semibold</value>
        </entry>
    </smartLocatorCollection>
    <smartLocatorEnabled>true</smartLocatorEnabled>
    <tag></tag>
    <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>