<?xml version="1.0" encoding="utf-8"?>
<WebElementEntity>
    <description>Generated by Katalon AI</description>
    <elementGuidId>d2878166-a52b-4013-a64a-7f2cabd54240</elementGuidId>
    <imagePath></imagePath>
    <name>item_removeLoadedForms</name>
    <selectorCollection>
        <entry>
            <key>XPATH</key>
            <value>//body/div[1]/div[1]/div[3]/main[1]/div[1]/div[2]/ul[1]/li[6]</value>
        </entry>
        <entry>
            <key>CSS</key>
            <value>[class="text-sm\ text-gray-700\ space-y-1"] &gt; li:nth-of-type(6)</value>
        </entry>
    </selectorCollection>
    <selectorMethod>XPATH</selectorMethod>
    <smartLocatorCollection>
        <entry>
            <key>SMART_LOCATOR</key>
            <value>.text-sm &gt; li:nth-child(6)</value>
        </entry>
    </smartLocatorCollection>
    <smartLocatorEnabled>true</smartLocatorEnabled>
    <tag></tag>
    <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>