<?xml version="1.0" encoding="utf-8"?>
<WebElementEntity>
    <description>Generated by Katalon AI</description>
    <elementGuidId>6a48d4da-84c8-4f20-b514-d07c49762540</elementGuidId>
    <imagePath></imagePath>
    <name>item_selectSiteId</name>
    <selectorCollection>
        <entry>
            <key>XPATH</key>
            <value>//body/div[1]/div[1]/div[3]/main[1]/div[1]/div[3]/ul[1]/li[1]</value>
        </entry>
        <entry>
            <key>CSS</key>
            <value>[class="text-sm\ text-gray-700\ space-y-1"] &gt; li:nth-of-type(1)</value>
        </entry>
    </selectorCollection>
    <selectorMethod>XPATH</selectorMethod>
    <smartLocatorCollection>
        <entry>
            <key>SMART_LOCATOR</key>
            <value>.text-sm &gt; li &gt;&gt; nth=0</value>
        </entry>
    </smartLocatorCollection>
    <smartLocatorEnabled>true</smartLocatorEnabled>
    <tag></tag>
    <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>