<?xml version="1.0" encoding="utf-8"?>
<WebElementEntity>
    <description>Generated by Katalon AI</description>
    <elementGuidId>50a8c55d-5c05-47e8-bfcd-765b0c571afe</elementGuidId>
    <imagePath></imagePath>
    <name>link_dragAndDrop</name>
    <selectorCollection>
        <entry>
            <key>XPATH</key>
            <value>//body/div[1]/div[1]/div[2]/nav[1]/div[2]/ul[1]/li[1]/a[1]</value>
        </entry>
        <entry>
            <key>CSS</key>
            <value>div:nth-of-type(2) &gt; [class="space-y-1"] &gt; li:nth-of-type(1) &gt; .flex</value>
        </entry>
        <entry>
            <key>BASIC</key>
            <value>//*[equals(@href,'https://base-component.aut.katalon.com/drag-drop.html') and equals(@text,'Drag &amp; Drop')]</value>
        </entry>
    </selectorCollection>
    <selectorMethod>XPATH</selectorMethod>
    <smartLocatorCollection>
        <entry>
            <key>SMART_LOCATOR</key>
            <value>[data-test=\"nav-drag-drop\"]</value>
        </entry>
    </smartLocatorCollection>
    <smartLocatorEnabled>true</smartLocatorEnabled>
    <tag></tag>
    <useRalativeImagePath>false</useRalativeImagePath>
    <webElementProperties>
        <isSelected>true</isSelected>
        <matchCondition>equals</matchCondition>
        <name>href</name>
        <type>Main</type>
        <value>https://base-component.aut.katalon.com/drag-drop.html</value>
        <webElementGuid>b3c57c63-de53-48c9-a1f5-f7dcfeed7326</webElementGuid>
    </webElementProperties>
    <webElementProperties>
        <isSelected>true</isSelected>
        <matchCondition>equals</matchCondition>
        <name>text</name>
        <type>Main</type>
        <value>Drag &amp; Drop</value>
        <webElementGuid>b3c57c63-de53-48c9-a1f5-f7dcfeed7326</webElementGuid>
    </webElementProperties>
</WebElementEntity>