<?xml version="1.0" encoding="utf-8"?>
<WebElementEntity>
    <description>Generated by Katalon AI</description>
    <elementGuidId>71978abc-0001-4b76-9473-839ece09c6c8</elementGuidId>
    <imagePath></imagePath>
    <name>link_comboBox</name>
    <selectorCollection>
        <entry>
            <key>XPATH</key>
            <value>//body/div[1]/div[1]/div[2]/nav[1]/div[3]/ul[1]/li[9]/a[1]</value>
        </entry>
        <entry>
            <key>CSS</key>
            <value>div:nth-of-type(3) li:nth-of-type(9) &gt; .flex</value>
        </entry>
        <entry>
            <key>BASIC</key>
            <value>//*[equals(@href,'https://base-component.aut.katalon.com/combobox.html') and equals(@text,'Combo Box')]</value>
        </entry>
    </selectorCollection>
    <selectorMethod>XPATH</selectorMethod>
    <smartLocatorCollection>
        <entry>
            <key>SMART_LOCATOR</key>
            <value>[data-test=\"nav-combobox\"]</value>
        </entry>
    </smartLocatorCollection>
    <smartLocatorEnabled>true</smartLocatorEnabled>
    <tag></tag>
    <useRalativeImagePath>false</useRalativeImagePath>
    <webElementProperties>
        <isSelected>true</isSelected>
        <matchCondition>equals</matchCondition>
        <name>href</name>
        <type>Main</type>
        <value>https://base-component.aut.katalon.com/combobox.html</value>
        <webElementGuid>c6fea543-e7ff-4781-88d7-91ce40e64f67</webElementGuid>
    </webElementProperties>
    <webElementProperties>
        <isSelected>true</isSelected>
        <matchCondition>equals</matchCondition>
        <name>text</name>
        <type>Main</type>
        <value>Combo Box</value>
        <webElementGuid>c6fea543-e7ff-4781-88d7-91ce40e64f67</webElementGuid>
    </webElementProperties>
</WebElementEntity>